CREATE TABLE PREGUNTAS(
ID INT NOT NULL AUTO_INCREMENT,
DESCRIPCION VARCHAR(100) NOT NULL,
TIPO VARCHAR(20) NOT NULL,
CONSTRAINT PK_PREGUNTAS PRIMARY KEY (ID)
);

CREATE TABLE OPCIONES_PREGUNTA(
ID INT NOT NULL AUTO_INCREMENT,
OPCION VARCHAR(5) NOT NULL,
DESCRIPCION VARCHAR(50) NOT NULL,
PREGUNTA_ID INT NOT NULL,
CONSTRAINT PK_OPCIONES PRIMARY KEY (ID),
CONSTRAINT FK_OPCIONES_PREGUNTAS FOREIGN KEY (PREGUNTA_ID) REFERENCES PREGUNTAS(ID)
);

CREATE TABLE RESPUESTAS_PREGUNTAS(
ID INT NOT NULL AUTO_INCREMENT,
RESPUESTA VARCHAR(100) NOT NULL,
PREGUNTA_ID INT NOT NULL,
USUARIO_ID INT NOT NULL,
CONSTRAINT PK_RESPUESTAS PRIMARY KEY (ID),
CONSTRAINT FK_RESPUESTAS_PREGUNTAS FOREIGN KEY (PREGUNTA_ID) REFERENCES PREGUNTAS(ID)
);

